### ISSUE TITLE
[Epic] 개발 환경 세팅하기

### ISSUE THREAD

**Issue by SujinEmilyCho** [woowacourse-teams/2020-saebyeok#2]
### 관련 이슈 목록
- [x] 모바일 앱을 구현할 기술스택 정하기 (#24)
- [x] Git initial commit 만들기 (#25)
- [x] Git Flow 전략 협의하기 (#26)
- [x] 코드 컨벤션 정하기 (#27)
- [x] Prettier, Eslint 스타일 설정 파일 작성하기 (#28)
- [x] 프레임워크 버전 선택하기(#29)
